services:
  caddy:
    image: ghcr.io/grrlopes/cashbox-pipe/cashbox-proxy:latest
    container_name: caddy_proxy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
    networks:
      - db_net
    dns:
      - 10.116.0.3
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
networks:
  db_net:
    driver: bridge
