name: Publish Cashbox image
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        docker build -t ghcr.io/${{ github.repository }}/cashbox-proxy:latest .
        docker push ghcr.io/${{ github.repository }}/cashbox-proxy:latest

    - name: Log out from GitHub Container Registry
      run: docker logout ghcr.io
